### ISSUE TITLE
ID field not editable in grid

### ISSUE THREAD

**Issue by kenjpete** [AccelerationNet/wp-db-table-editor#16]
Great plugin! Works really well. I just have one issue I cannot figure out. When I load my table in the grid, I cannot edit the ID field (int, primary). Which isn't really a problem except that when I add a record I can't add a number for the ID field. When I double-click in the ID field it doesn't become editable.

I went through the documentation to add the interface. Here is my function code from my functions.php file:

if(function_exists('add_db_table_editor')) {

add_db_table_editor(array( 
	'title'=>'Staff Directory', 
	'table'=>'staff', 
	'id_column'=>'ID',
	'edit_cap'=>'Editor',
	'sql'=>'SELECT * FROM staff ORDER BY Last' ));

}

Am I missing a parameter that would enable that? Also I checked the structure of the 'staff' table, the ID field is not set up as an auto increment field.

Any thoughts?

**Comment by bobbysmith007** [comment]
For my purposes all database tables have an AUTO_INCREMENT key, so i have not experienced this bug, though I am aware of it.  The unique primary key cannot be edited by this plugin.  This key is used to ensure that we update the proper data and tracks data between client and server.  While with some extra work, I am sure it could be made to work, for simplicity its not currently implemented.

Is it not possible to make the column AUTO_INCREMENT such that you would not need to provide data for that column?  Otherwise, I guess we would need to special case "new" rows such that the id can be edited on those (which is probably not simple either).

Patches are accepted if you want to dive in and fix this.  Otherwise it will probably be a back burner thing till it comes up for me.

**Comment by kenjpete** [comment]
Ok, I adjusted my database so that the ID field is auto increment. Now, any new rows added get a unique ID field added after I save the row. On the rare occasion that I need to edit an existing ID I will go into the MYSQL database and do it manually.....thanks!

**Comment by bobbysmith007** [comment]
Awesome! Definitely the easiest solution :)
