### ISSUE TITLE
columnNameMap is not working

### ISSUE THREAD

**Issue by edohi** [AccelerationNet/wp-db-table-editor#19]
I'm using the following:

if(function_exists('add_db_table_editor')){
  add_db_table_editor(array(
    'title'=>'Seminars',
    'table'=>'wp_dbt_courses',
    'sql'=>'SELECT coursesID,session_group,cost,session_time,session_date,session_time_to,session_date_to,details,address_city,instructor,instructor2,language FROM wp_dbt_courses',
    'id_column'=>'coursesID',
    'hide_columns'=>'coursesID',
    'columnNameMap'=>'Seminar ID, Group No, Cost, Time From, Date From, Time To, Date To, Details, City, Instructor, Instructor2, Language'
));
}

but the columnNameMap is not working, the columns aliases are not shown on the interface. Any idea what am I doing wrong ?

**Comment by bobbysmith007** [comment]
Your issue is that columnNameMap, is intended to be an A_ARRAY (hash table)  so:

`columnNameMap=>Array('coursesID'=>'Seminar ID', 'session_group'=>'Group No' ...`

Maybe not the best implementation of this, but it allows selectively aliasing single columns, which I think is what I needed at the time.

**Comment by bobbysmith007** [comment]
Added a note to the docs, 

cheers and thanks!

**Comment by edohi** [comment]
Thanks a lot for the super-fast reply! ;o)

**Comment by edohi** [comment]
It worked!
