### ISSUE TITLE
How do I export table data or records to PDF

### ISSUE THREAD

**Issue by bondjames12345677** [AccelerationNet/wp-db-table-editor#22]
Good Day Every One!

I just want to know that, is there any possibilities that we can export the table data or records in PDF instead of CSV? if yes then how?

I really appreciate if any body help me out about it! thanks :)

**Comment by bobbysmith007** [comment]
The data is not really displayed in a "for print" format.  The easiest way to handle this would be to create a custom page on your site that displays your data in the desired format, then you a PDF printer driver to print that webpage to a pdf.  I have no plans of integrating any pdf export feature, because it would essentially be the same complexity scale as this plugin and can be handled entirely in a separate plugin ("WP DB PDF Exporter anyone?")

**Comment by bondjames12345677** [comment]
Thank You Very Much for your suggestion & I must say its such a wonderful Plugin!  Thanks for the Plugin once again.
