### ISSUE TITLE
Undefined index: where and column

### ISSUE THREAD

**Issue by akela92** [AccelerationNet/wp-db-table-editor#24]
Good morning everyone,
I've been using this great plugin without any problems until a few days ago. I noticed that even though I can edit a value in the admin GUI, when I press “Save x changes” nothing saves in my DB.
I've been debbugin since I noticed the error and WP tells me that where and column are undefined indexes. I have tried to uninstall the plugin and installing it fresh again but still no luck.
I leave a snapshot of the error in case it helps.

![error](https://cloud.githubusercontent.com/assets/8903563/20479464/9462b37a-afde-11e6-99fa-bb1fa9bf08de.PNG)

Thanks in advance

**Comment by akela92** [comment]
Hello again,

I've sort of solved the problem. The query I was using was taking values from 3 different tables, and therefore I think that it couldn't choose to which table it should store the changes. Is there a way to use 3 tables in a query?
By the way, the index error is still there but it doesn't affect to the plugin, is it suppose to be that way?

Thanks again and great plugin

**Comment by bobbysmith007** [comment]
You will have to write custom save/delete hooks for this table in order to save data to a joined view.  If you are only editing data from one of the tables you can probably get it to use the default save hooks by making all the joined columns un-editable.  

There is an example of writing custom save hooks in the examples folder here: 
https://github.com/AccelerationNet/wp-db-table-editor/blob/master/examples/cf7dbsubmit_integration.php#L76

----

The undefined indexes are probably not causing any actual problems (they rarely do), but are more stylistic snafus. (Though I will look into them) .

----

I am closing, but if you need more help feel free to keep asking

**Comment by bobbysmith007** [comment]
And actually, those notices are supressed, I didnt realize there was a way to get suppressed notices.  I thought that `@$arr['maybe_key_exists']` was a reasonable way to get a value from an array.  I know I could use `isset` but every other way I have seen to type this is longer than the `@` variant

**Comment by akela92** [comment]
Thanks for the fast answer, I will try as you say with the custom hooks. For debugging I am using this fantastic plugin [Query Monitor](https://wordpress.org/plugins/query-monitor/).
Thanks again and great plugin
