### ISSUE TITLE
Editors can't edit 

### ISSUE THREAD

**Issue by jakerbug** [AccelerationNet/wp-db-table-editor#8]
I've got the plugin and everything is working great from the main admin account. However, I created "editor" accounts to delegate admin duties, and those users do not have the capability to edit/add/remove. They can view and search the table, but that's all. I don't have any of the permission arguments set, which I understood from the documentation defaults to unlimited access.

Any ideas why this isn't working?

Thanks!
Jake

**Comment by bobbysmith007** [comment]
Its supposed to default to `edit_others_posts` for view and edit defaults to whether or not you can see the grid. Role `editor` users should have that capability by default, and it seems they do since they can see the grid.

I tried this on a test blog (at a guess since you didnt provide the actual config section), and could not recreate the issue (my `editor` user could both see and edit the grid).  

Debugging suggestions:
In the HTML source, you can see the full json being used to initialize the DBTableEditor instance in javascript.  If you copy and paste that (remove the data please) I might be able to spot something wrong.

Check the js error console (F12 in modern browsers) for javascript errors, that might point the way.

Admin can edit but editors can't, sounds very strange, as the default permission is shared between them.  Verify that its the same interface maybe (ie, you didnt check tbl1 with admin and tbl2 with editor).  Its a long shot but a mistake I have made :/  Maybe the `noedit` option is being set somehow?

**Comment by jakerbug** [comment]
Here's the json:

DBTableEditor.onload({"baseUrl":"http:\/\/www.vintageatlanticwine.com\/SITE\/wp-content\/plugins\/wp-db-table-editor","data": ***DATA REMOVED*** ,"table":"wp_toqs_wineries","title":"Wineries","dataFn":null,"id":"wp_toqs_wineries","cap":"edit_others_posts","jsFile":null,"noedit":null,"editcap":true,"noedit_columns":null,"hide_columns":"id","default_values":null,"columnFilters":null,"columnNameMap":null,"insert_cb":null,"update_cb":null,"delete_cb":null,"id_column":"id","auto_date":true});

No javascript errors.... I tried setting 'noedit' => false as well, but had not luck either way...

**Comment by jakerbug** [comment]
FYI - I set "$noedit = false;" on line 197 and it's working, so for some reason noedit was being set to true. I'm sure this is not ideal, as it looks like it will allow access indiscriminately, however, it's a workaround that works for me...

**Comment by bobbysmith007** [comment]
In my editor json, editcap is null rather than true.  I see that noedit is null in both of ours.  I think this is the problem, though I cant see why editcap would be true rather than null.  No where in code is this variable set directly and its not referenced in js.  

The noedit variable is being set to true in 197 because 
`$cur->editcap && !current_user_can($cur->editcap)` is identically false  if `$cur->editcap === true`

Do you see anything that might cause this in your configuration? A better work around might be to explicitly set editcap = false in your configuration (though I am still not sure why it would be different in your setup).

**Comment by jakerbug** [comment]
That's my fault - I set that to true in functions.php because I misunderstood what it did. I removed it so that it uses the default now, and I changed the code of line 197 in db-table-editor.php back to the way it was, and it's working fine. 

Sorry for the confusion. Just wanted to let you know it was my fault!

**Comment by bobbysmith007** [comment]
So glad we got you straightened out :)  Hope the plugin serves you well
