### ISSUE TITLE
Editor does not save edits

### ISSUE THREAD

**Issue by pierstorff** [AccelerationNet/wp-db-table-editor#9]
I have the table editor set up as per example

 add_db_table_editor(array(
    'title'=>'My Title',
    'table'=>'my_table',
    'sql'=>'SELECT * FROM my_table ORDER BY id ASC'
 ));

(I have also tried to explictly set editcap to edit posts, but that didn't change a thing). The table is just a few text fields and a numeric auto-increment id as primary index.

I can see the table grid and export to csv. However edits to table rows are not being saved. I.e. klick a cell until it's editable, enter a value, hit the "save changes" button. The change is reflected in the interface (and there is a "success" message in the console), but the changed value is not written to the database (so it's lost when I reload the page).

Also I cannot create new rows (I'm not sure how this is supposed to work, the "new" button does not do anything). 

There are no error messages. I tried this as admin user in Wordpress.

I assume I set this up wrongly, but I'm not sure what I could do better. Help would be appreciated.

Thank you.

Eike

**Comment by bobbysmith007** [comment]
Sorry I had not responded... this must have slipped through my cracks.

Try turning on wp-debugging `define( 'WP_DEBUG', true ); define( 'WP_DEBUG_DISPLAY', true );` and see if there are any errors when trying to save.  These will show up in the javascript consoles net tab under the response to the http request  Otherwise you might need to set id_column to the id (though it defaults to `id` which seems like it should work from your example).

The new button should simply select the empty row at the bottom of the grid, allowing you to start entering data.

**Comment by bobbysmith007** [comment]
Closing since this person never responded and I have no evidence of further troubles.  I have also fixed many bugs since then, so hopefully this is one
